language: node_js

node_js:
  - '12'
  - '10'
  - '8'

matrix:
  include:
    - node_js: "13"
      env: "NVM_NODEJS_ORG_MIRROR=https://nodejs.org/download/nightly"
  allow_failures:
    # Allow the nightly installs to fail
    - env: "NVM_NODEJS_ORG_MIRROR=https://nodejs.org/download/nightly"

cache:
  directories:
    - $HOME/.npm
    - $HOME/.yarn-cache
    - node_modules

script:
  - lerna run lint
